version: '3.8'

networks:
  default:
    name: wvcapp

services:
  nginx:
    container_name: nginx
    build:
      context: ./utils/nginx
    restart: unless-stopped
    volumes:
      - ./utils/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./utils/nginx/localhost-cert.pem:/ssl/localhost-cert.pem:ro
      - ./utils/nginx/localhost-privkey.pem:/ssl/localhost-privkey.pem:ro
      - ./utils/nginx/jaeger-nginx-config.json:/etc/jaeger-nginx-config.json:ro
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    extra_hosts:
      - host.docker.internal:host-gateway

